language: python
python: 2.7
sudo: false
env:
- TOXENV=py27
- TOXENV=py34

addons:
  apt:
    packages:
    - python-numpy
    - python-scipy
    - libatlas-base-dev
    - liblapack-dev
    - gfortran

install:
- pip install -U pip tox codecov

script: travis_wait tox

after_success:
  - codecov

cache:
  directories:
    - $HOME/.cache/pip
