language: python
python: 2.7
sudo: false
env:
- TOXENV=py27

addons:
  apt:
    packages:
    - python-numpy
    - python-scipy
    - libatlas-base-dev
    - liblapack-dev
    - gfortran

install:
- pip install -U tox

script: tox

cache:
  directories:
    - .tox
